Fvo.Store.UI/Controllers/ContaController.cs
using Fvo.Store.Data.EF.Repositories;
using Fvo.Store.Domain.Contracts.Repositories;
using Fvo.Store.Domain.Helpers;
using Fvo.Store.UI.ViewModel;
using System.Web.Mvc;
using System.Web.Security;

namespace Fvo.Store.UI.Controllers
{
    public class ContaController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        public ContaController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        // GET: Conta
        [HttpGet]
        public ActionResult Index(string returnURL)
        {
            var model = new LoginVM() { ReturnURL = returnURL };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(LoginVM model)
        {
            var usuario = _usuarioRepository.Get(model.Email);
            if (usuario == null)
                ModelState.AddModelError("Email", "O e-mail não foi localizado");
            else
            {
                if (usuario.Senha != model.Senha.Ecrypt())
                ModelState.AddModelError("Senha", "Senha inválida");
            }
                
            if (ModelState.IsValid)
            {
                FormsAuthentication.SetAuthCookie(model.Email, model.PermanecerLogado);
                if (!string.IsNullOrEmpty(model.ReturnURL) && Url.IsLocalUrl(model.ReturnURL))
                {
                    return Redirect(model.ReturnURL);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
           
        }
    }
}

Fvo.Store.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fvo.Store.UI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Sobre()
        {
            return View();
        }
    }
}

Fvo.Store.UI/Controllers/ProdutosController.cs
using Fvo.Store.Domain.Contracts.Repositories;
using Fvo.Store.UI.ViewModel.Produtos.AddEdit;
using Fvo.Store.UI.ViewModel.Produtos.AddEdit.Maps;
using Fvo.Store.UI.ViewModel.Produtos.Index.Maps;
using System.Web.Mvc;

namespace Fvo.Store.UI.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly ITipoDeProdutoRepository _tipoDeProdutoRepository;
       
        public ProdutosController(IProdutoRepository produtoRepository, ITipoDeProdutoRepository tipoDeProdutoRepository)
        {
            _produtoRepository = produtoRepository;
            _tipoDeProdutoRepository = tipoDeProdutoRepository;
        }
        // GET: Produtos
        public ActionResult Index()
        {
            var produtos = _produtoRepository.Get().ToProdutoIndexVM();
            return View(produtos);
        }

        [HttpGet]
        public ActionResult AddEdit(int? id)
        {
            var produto = new ProdutoAddEditVM();
            if (id != null)
            {
                produto = _produtoRepository.Get((int)id).ToProdutoAddEditVM();
            }
            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;
            return View(produto);
        }

     
        [HttpPost]
        public ActionResult AddEdit(ProdutoAddEditVM produtoVM)
        {
            var produto = produtoVM.ToProduto();

            if (ModelState.IsValid)
            {
                if (produto.Id == 0)
                {
                    _produtoRepository.Add(produto);
                }
                else
                {
                    _produtoRepository.Edit(produto);
                }

                return RedirectToAction("Index");
            }

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;

            return View(produto);

        }

        public ActionResult DelProd(int id)
        {
            var produto = _produtoRepository.Get(id);
            if (produto == null)
            {
                return HttpNotFound();
            }

            _produtoRepository.Delete(produto);
            return null;

            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
           
        }
    }
}

Fvo.Store.UI/Views/Conta/Index.cshtml
@model Fvo.Store.UI.ViewModel.LoginVM
@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <form method="post" class="col-md-6 col-sm-12">
        <div class="form-group">
            <label>E-mail</label>
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", autofocus = "" })
            @Html.ValidationMessageFor(model => model.Email, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label>Senha</label>
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control", autofocus = "" })
            @Html.ValidationMessageFor(model => model.Senha, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.CheckBoxFor(model => model.PermanecerLogado, new { @class = "form-check-input" })
            @Html.LabelFor(model => model.PermanecerLogado)
        </div>

        <div class="form-group">
            <button class="btn btn-outline-secondary">
                Salvar
            </button>
            <a class="btn btn-outline-warning" href="@Url.Action("Index", "Home")">Cancelar</a>
        </div>
    </form>
</div>
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Fvo.Store.UI/Views/Home/Index.cshtml
<h2>FVO Store</h2>
<p>Bem vindo ao melhor e-commerce da web</p>

Fvo.Store.UI/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}

<h2>Sobre</h2>
<p>Descrição do site</p>

Fvo.Store.UI/Views/Produtos/AddEdit.cshtml
@model  Fvo.Store.UI.ViewModel.Produtos.AddEdit.ProdutoAddEditVM

@{
    ViewBag.Title = $"{(Model.Id == 0 ? "Adicionar" : "Editar")} Produto";
}
<h2>@ViewBag.Title</h2>

<form action="~/Produtos/AddEdit/@Model.Id" method="post">
    <div class="form-group">
        <label for="txtNome">Nome</label>
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", autofocus = "" })
        @Html.ValidationMessageFor(m => m.Nome, null, new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label for="txtPreco">Preço</label>
        @Html.TextBoxFor(m => m.Preco, new { @class = "form-control", autofocus = "" })
        @Html.ValidationMessageFor(m => m.Preco, null, new { @class = "text-danger" })

    </div>

    <div class="form-group">
        <label for="txtTipo">Tipo</label>
        @Html.DropDownListFor(m => m.TipoDeProdutoId, new SelectList(ViewBag.Tipos, "Id", "Nome"), "Selecione...", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TipoDeProdutoId, null, new { @class = "text-danger" })

    </div>

    <div class="form-group">
        <label for="txtQtde">Quantidade</label>
        @Html.TextBoxFor(m => m.Qtde, new { @class = "form-control", autofocus = "" })
        @Html.ValidationMessageFor(m => m.Qtde, null, new { @class = "text-danger" })

    </div>

    <div class="form-group mt-1">
        <button class="btn btn-primary">Salvar</button>
        <a href="@Url.Action("Index")" class="btn btn-outline-secondary">Cancelar</a>
    </div>
</form>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Fvo.Store.UI/Views/Produtos/Index.cshtml
@using Fvo.Store.UI.ViewModel.Produtos.Index
<h2>Listagem de Produtos</h2>


<div class="mb-3">
    <a class="btn btn-outline-info" href="@Url.Action("AddEdit")">Novo Produto</a>
</div>
<table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Tipo</th>
            <th>Qtde</th>
            <th>Data do Cadastro</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (ProdutoIndexVM produto in Model)
        {
            <tr id="produto-@produto.Id">
                <td>@produto.Nome</td>
                <td>@produto.Preco.ToString("C2")</td>
                <td>@produto.Tipo</td>
                <td>@produto.Qtde</td>
                <td>@produto.DataCadastro</td>
                <td class="btn-group">
                    <a href="@Url.Action("AddEdit", new { id = produto.Id})" class="btn btn-sm btn-outline-success"><i class="fas fa-edit"></i> Editar</a>
                    <button class="btn btn-sm btn-outline-danger" onclick="DelProd(@produto.Id,'@produto.Nome')"><i class="fas fa-trash"></i> Excluir</button>
                </td>
                
            </tr>
        }

    </tbody>
</table>

<div data-id="0" class="modal" tabindex="-1" id="delModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir produto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir o <strong><span id="nomeProdModal"></span></strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button onclick="ConfirmeDelProd()" type="button" class="btn btn-primary" >Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function DelProd(id, nome) {
        //let resp = confirm(`Deseja excluir o produto '${nome}' ?`);
        //if (resp) {
        //    console.log(`Excluir ${id}`)
        //    ConfirmeDelProd(id)
        //}

        $('#nomeProdModal').text(nome)
        $('#delModal').data('id', id).modal('show')
    }

    function ConfirmeDelProd() {
        let id = $('#delModal').data('id')

        let xhr = new XMLHttpRequest()
        const url = `Produtos/DelProd/${id}`

        xhr.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 404) {
                $('#delModal').data('id', id).modal('hide')
                toastr.error('Produto não localizado', 'Fvo Store')
            }
            if (this.readyState === 4 && this.status === 200) {
                //remover do html
                let tr = document.querySelector(`#produto-${id}`)
                if (tr !== null) {
                    tr.remove()
                }
                $('#delModal').data('id', id).modal('hide')
                toastr.success('Produto excluído com sucesso', 'Fvo Store')

            }
        }

        xhr.open('get', url)
        xhr.send()
    }

    
</script>

Fvo.Store.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/fontawesome/all.min.js"></script>
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <title>FVO Store</title>
</head>
<body>

    @Html.Partial("_menu")
    @*//conteudo das views*@
    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer class="footer bg-info footer-custom">
        <div class="container">
            <span class="text-muted">&copy; @DateTime.Now.Year Fvo Store</span>
        </div>
    </footer>

    <script src="~/Scripts/jquery-3.6.3.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Fvo.Store.UI/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="#">FN Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">Página Inicial</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Produtos")">Produtos</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Sobre","Home")">Sobre</a>
            </li>

        </ul>

        <ul class="navbar-nav ml-auto">

            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @User.Identity.Name
                    </a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("LogOut", "Conta")">LogOut</a>
                </li>
             }
            else
            {
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","Conta")">Efetuar Login</a>
                </li>
            }
        </ul>


    </div>
</nav>